import { z } from "zod";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, NotFoundError, apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { applyStockMovement } from "@/lib/server/inventory";

const schema = z.object({ version: z.number().int().positive(), lines: z.array(z.object({ lineId: z.string().cuid(), quantity: z.string().regex(/^\d+(\.\d{1,3})?$/) })).min(1).max(100), notes: z.string().trim().max(500).optional() });
export async function POST(request: Request, { params }: { params: Promise<{ transferId: string }> }) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.transfer"); const input = await parseJson(request, schema); const { transferId } = await params; const result = await db.$transaction(async (tx) => { const transfer = await tx.stockTransfer.findFirst({ where: { id: transferId, companyId: access.companyId }, include: { lines: true } }); if (!transfer) throw new NotFoundError("Stock transfer was not found."); requireStation(access, transfer.destinationStationId, true); if (transfer.status !== "DISPATCHED" || transfer.version !== input.version) throw new AppError("TRANSFER_CONFLICT", "Transfer is no longer awaiting receipt.", 409); if (input.lines.length !== transfer.lines.length) throw new AppError("INVALID_TRANSFER_LINES", "Every dispatched line requires a received quantity.", 422); for (const received of input.lines) { const line = transfer.lines.find((item) => item.id === received.lineId); if (!line || line.quantityDispatched.lt(received.quantity) || Number(received.quantity) < 0) throw new AppError("INVALID_RECEIPT_QUANTITY", "A received quantity is invalid.", 422); if (Number(received.quantity) > 0) await applyStockMovement(tx, { companyId: access.companyId, stationId: transfer.destinationStationId, productId: line.productId, batchId: line.batchId, movementType: "TRANSFER_IN", quantityDelta: received.quantity, referenceType: "StockTransfer", referenceId: transfer.id, reason: transfer.reason, occurredById: access.userId }); await tx.stockTransferLine.update({ where: { id: line.id }, data: { quantityReceived: received.quantity } }); } const changed = await tx.stockTransfer.updateMany({ where: { id: transfer.id, status: "DISPATCHED", version: input.version }, data: { status: "RECEIVED", receivedById: access.userId, receivedAt: new Date(), notes: input.notes ?? transfer.notes, version: { increment: 1 } } }); if (changed.count !== 1) throw new AppError("TRANSFER_CONFLICT", "Transfer was received concurrently.", 409); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: transfer.destinationStationId, action: "inventory.transfer.received", entityType: "StockTransfer", entityId: transfer.id, requestId, before: transfer, after: { status: "RECEIVED", lines: input.lines } }); return tx.stockTransfer.findUniqueOrThrow({ where: { id: transfer.id }, include: { lines: true } }); }, { isolationLevel: "Serializable", timeout: 30000, maxWait: 15000 }); return apiSuccess(result, requestId); } catch (error) { return apiFailure(error, requestId); } }
