import { z } from "zod";
import { Prisma } from "@/lib/generated/prisma/client";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, apiFailure, apiSuccess, parseJson, parsePagination, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { allocateSequence } from "@/lib/server/sequence";

const schema = z.object({ stationId: z.string().cuid(), reason: z.string().trim().min(5).max(500), lines: z.array(z.object({ productId: z.string().cuid(), batchId: z.string().cuid().optional(), countedQuantity: z.string().regex(/^\d+(\.\d{1,3})?$/) })).min(1).max(100) });
export async function GET(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.view"); const url = new URL(request.url); const { page, pageSize, skip, take } = parsePagination(url.searchParams); const where = { companyId: access.companyId, ...(access.companyWide ? {} : { stationId: { in: [...access.stationIds] } }) }; const [items, total] = await Promise.all([db.inventoryAdjustment.findMany({ where, include: { station: { select: { id: true, code: true, name: true } }, lines: { include: { product: { select: { id: true, code: true, name: true } } } } }, orderBy: { requestedAt: "desc" }, skip, take }), db.inventoryAdjustment.count({ where })]); return apiSuccess(items, requestId, { page, pageSize, total }); } catch (error) { return apiFailure(error, requestId); } }
import { dispatchNotification } from "@/lib/server/notifications";
export async function POST(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.adjust"); const input = await parseJson(request, schema); requireStation(access, input.stationId, true); const adjustment = await db.$transaction(async (tx) => { const adjustmentNumber = await allocateSequence(tx, { companyId: access.companyId, stationId: input.stationId, documentType: "INVENTORY_ADJUSTMENT", prefix: "ADJ", includeDate: true, padding: 6 }); const lines = []; for (const line of input.lines) { const balance = await tx.inventoryBalance.findUnique({ where: { stationId_productId_batchKey: { stationId: input.stationId, productId: line.productId, batchKey: line.batchId ?? "" } } }); const expected = balance?.quantity ?? new Prisma.Decimal(0); const counted = new Prisma.Decimal(line.countedQuantity); lines.push({ productId: line.productId, batchId: line.batchId, expectedQuantity: expected, countedQuantity: counted, quantityDelta: counted.minus(expected) }); } if (lines.every((line) => line.quantityDelta.isZero())) throw new AppError("NO_ADJUSTMENT", "Counted quantities already match the ledger.", 422); const created = await tx.inventoryAdjustment.create({ data: { companyId: access.companyId, stationId: input.stationId, adjustmentNumber, status: "PENDING_APPROVAL", reason: input.reason, requestedById: access.userId, lines: { create: lines } }, include: { lines: true } }); await tx.approvalRequest.create({ data: { companyId: access.companyId, stationId: input.stationId, entityType: "InventoryAdjustment", entityId: created.id, action: "inventory.approve_adjustment", requestedById: access.userId, assignedRoleKey: "INVENTORY_APPROVER", requestReason: input.reason, payload: { adjustmentNumber } } }); await dispatchNotification(tx, { companyId: access.companyId, stationId: input.stationId, targetRoles: ["SUPER_ADMIN", "ADMIN", "OPERATIONS_MANAGER"], type: "INVENTORY_APPROVAL", title: "Inventory Adjustment Request", message: `Adjustment ${adjustmentNumber} requires approval.`, entityType: "InventoryAdjustment", entityId: created.id }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: input.stationId, action: "inventory.adjustment.requested", entityType: "InventoryAdjustment", entityId: created.id, reason: input.reason, requestId, after: created }); return created; }); return apiSuccess(adjustment, requestId, { created: true, requiresApproval: true }); } catch (error) { return apiFailure(error, requestId); } }
