import { z } from "zod";

import { requireAccess, requirePermission } from "@/lib/server/access";
import { apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";

const setupSchema = z.discriminatedUnion("type", [z.object({ type: z.literal("ACCOUNT"), code: z.string().trim().min(2).max(30), name: z.string().trim().min(2).max(120), accountType: z.string().trim().min(2).max(50), paymentMethodId: z.string().cuid().optional() }), z.object({ type: z.literal("CATEGORY"), code: z.string().trim().min(2).max(30), name: z.string().trim().min(2).max(120), direction: z.enum(["DEBIT", "CREDIT"]) })]);
export async function GET(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "finance.view"); const [accounts, categories, methods, periods] = await Promise.all([db.financialAccount.findMany({ where: { companyId: access.companyId, isActive: true }, include: { paymentMethod: true }, orderBy: { name: "asc" } }), db.financialCategory.findMany({ where: { companyId: access.companyId, isActive: true }, orderBy: { name: "asc" } }), db.paymentMethod.findMany({ where: { companyId: access.companyId, isActive: true }, orderBy: { displayOrder: "asc" } }), db.financialPeriod.findMany({ where: { companyId: access.companyId }, orderBy: { startsAt: "desc" }, take: 24 })]); return apiSuccess({ accounts, categories, paymentMethods: methods, periods }, requestId); } catch (error) { return apiFailure(error, requestId); } }
export async function POST(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "settings.manage"); const input = await parseJson(request, setupSchema); const record = await db.$transaction(async (tx) => { const created = input.type === "ACCOUNT" ? await tx.financialAccount.create({ data: { companyId: access.companyId, code: input.code.toUpperCase(), name: input.name, accountType: input.accountType, paymentMethodId: input.paymentMethodId } }) : await tx.financialCategory.create({ data: { companyId: access.companyId, code: input.code.toUpperCase(), name: input.name, type: input.direction } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, action: `finance.${input.type.toLowerCase()}.created`, entityType: input.type, entityId: created.id, requestId, after: created }); return created; }); return apiSuccess(record, requestId, { created: true }); } catch (error) { return apiFailure(error, requestId); } }
