import { z } from "zod";

import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, apiFailure, apiSuccess, parseJson, parsePagination, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { allocateSequence } from "@/lib/server/sequence";

const agentSchema = z.object({ homeStationId: z.string().cuid(), customerId: z.string().cuid().optional(), name: z.string().trim().min(2).max(180), contactName: z.string().trim().min(2).max(120), phone: z.string().trim().min(7).max(30), email: z.string().email().optional(), address: z.string().trim().max(500).optional(), creditLimit: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0") });
export async function GET(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "agents.view"); const url = new URL(request.url); const { page, pageSize, skip, take } = parsePagination(url.searchParams); const stationId = url.searchParams.get("stationId") ?? undefined; if (stationId) requireStation(access, stationId); const where = { companyId: access.companyId, ...(stationId ? { homeStationId: stationId } : access.companyWide && !access.stationIds.size ? {} : { homeStationId: { in: [...access.stationIds] } }) }; const [items, total] = await Promise.all([db.agent.findMany({ where, include: { homeStation: { select: { id: true, code: true, name: true } }, wallet: true, customer: { select: { id: true, customerNumber: true, displayName: true } }, _count: { select: { sales: true, bookings: true } } }, orderBy: { name: "asc" }, skip, take }), db.agent.count({ where })]); return apiSuccess(items, requestId, { page, pageSize, total }); } catch (error) { return apiFailure(error, requestId); } }
export async function POST(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "agents.manage"); const input = await parseJson(request, agentSchema); requireStation(access, input.homeStationId, true); if (input.customerId && !(await db.customer.findFirst({ where: { id: input.customerId, companyId: access.companyId, status: "ACTIVE" } }))) throw new AppError("INVALID_CUSTOMER", "Linked customer is unavailable.", 422); const agent = await db.$transaction(async (tx) => { const agentNumber = await allocateSequence(tx, { companyId: access.companyId, stationId: input.homeStationId, documentType: "AGENT", prefix: "AGT", includeDate: false, padding: 5 }); const created = await tx.agent.create({ data: { companyId: access.companyId, homeStationId: input.homeStationId, customerId: input.customerId, agentNumber, name: input.name, contactName: input.contactName, phone: input.phone, email: input.email, address: input.address, creditLimit: input.creditLimit, createdById: access.userId, wallet: { create: {} } }, include: { wallet: true } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: input.homeStationId, action: "agent.created", entityType: "Agent", entityId: created.id, requestId, after: created }); return created; }, { isolationLevel: "Serializable", timeout: 30_000, maxWait: 15_000 }); return apiSuccess(agent, requestId, { created: true }); } catch (error) { return apiFailure(error, requestId); } }
