export const PERMISSIONS = [
  ["dashboard.view", "dashboard", "view", "View permission-scoped dashboards", false],
  ["dashboard.view_consolidated", "dashboard", "view_consolidated", "View consolidated company dashboards", true],
  ["stations.view", "stations", "view", "View stations and performance", false],
  ["stations.manage", "stations", "manage", "Create and configure stations", true],
  ["stations.create", "stations", "create", "Create stations", true],
  ["stations.update", "stations", "update", "Update station configuration", true],
  ["stations.disable", "stations", "disable", "Disable a station", true],
  ["stations.assign_manager", "stations", "assign_manager", "Assign station managers", true],
  ["stations.view_performance", "stations", "view_performance", "View station performance", true],
  ["users.view", "users", "view", "View users", false],
  ["users.manage", "users", "manage", "Create and update users", true],
  ["users.reset_password", "users", "reset_password", "Reset another user's password", true],
  ["users.revoke_session", "users", "revoke_session", "Revoke active sessions", true],
  ["roles.view", "roles", "view", "View roles and permissions", false],
  ["roles.manage", "roles", "manage", "Create roles and grant permissions", true],
  ["staff.view", "staff", "view", "View staff directory", false],
  ["staff.manage", "staff", "manage", "Create and update staff records", true],
  ["staff.create", "staff", "create", "Create staff records", true],
  ["staff.update", "staff", "update", "Update staff records", true],
  ["staff.change_status", "staff", "change_status", "Change employment status", true],
  ["staff.manage_documents", "staff", "manage_documents", "Manage staff documents", true],
  ["staff.view_sensitive", "staff", "view_sensitive", "View salary, ID, and next-of-kin fields", true],
  ["customers.view", "customers", "view", "View customer records", false],
  ["customers.manage", "customers", "manage", "Create and update customers", false],
  ["customers.create", "customers", "create", "Create customers", false],
  ["customers.update", "customers", "update", "Update customers", false],
  ["customers.view_history", "customers", "view_history", "View cross-module customer history", false],
  ["customers.view_sensitive", "customers", "view_sensitive", "View protected customer identifiers", true],
  ["customers.merge", "customers", "merge", "Merge duplicate customer records", true],
  ["inventory.view", "inventory", "view", "View catalogue and balances", false],
  ["inventory.create_product", "inventory", "create_product", "Create products", false],
  ["inventory.update_product", "inventory", "update_product", "Update products", true],
  ["inventory.stock_in", "inventory", "stock_in", "Receive stock", false],
  ["inventory.stock_out", "inventory", "stock_out", "Issue stock", false],
  ["inventory.transfer", "inventory", "transfer", "Transfer stock between stations", true],
  ["inventory.adjust", "inventory", "adjust", "Request inventory adjustments", true],
  ["inventory.approve_adjustment", "inventory", "approve_adjustment", "Approve inventory adjustments", true],
  ["inventory.view_cost", "inventory", "view_cost", "View purchase cost and valuation", true],
  ["purchases.view", "purchases", "view", "View suppliers and purchases", false],
  ["purchases.manage", "purchases", "manage", "Create and approve purchase orders", true],
  ["sales.view", "sales", "view", "View sales", false],
  ["sales.create", "sales", "create", "Post POS sales", false],
  ["sales.discount", "sales", "discount", "Apply controlled discounts", true],
  ["sales.cancel", "sales", "cancel", "Cancel or reverse a sale", true],
  ["sales.refund", "sales", "refund", "Create refunds", true],
  ["cargo.view", "cargo", "view", "View cargo and AWB records", false],
  ["cargo.manage", "cargo", "manage", "Create and update cargo records", false],
  ["cargo.reprint", "cargo", "reprint", "Reprint cargo labels", false],
  ["cargo.correct", "cargo", "correct", "Correct issued cargo labels", true],
  ["cargo.create", "cargo", "create", "Create cargo shipments", false],
  ["cargo.update_draft", "cargo", "update_draft", "Update draft cargo shipments", false],
  ["cargo.change_status", "cargo", "change_status", "Change cargo status", false],
  ["cargo.edit_label", "cargo", "edit_label", "Correct or edit issued labels", true],
  ["cargo.cancel", "cargo", "cancel", "Cancel cargo shipments", true],
  ["agents.view", "agents", "view", "View agents", false],
  ["agents.manage", "agents", "manage", "Create and update agents", true],
  ["wallet.view", "wallet", "view", "View agent wallet balances", true],
  ["wallet.post", "wallet", "post", "Post wallet deposits and debits", true],
  ["wallet.adjust", "wallet", "adjust", "Adjust or reverse wallet entries", true],
  ["wallet.change_credit_limit", "wallet", "change_credit_limit", "Change agent wallet credit limits", true],
  ["finance.view", "finance", "view", "View cashbook and finance", true],
  ["finance.post_income", "finance", "post_income", "Post income", true],
  ["finance.post_expense", "finance", "post_expense", "Post expenses", true],
  ["finance.approve", "finance", "approve", "Approve financial postings", true],
  ["finance.reconcile", "finance", "reconcile", "Reconcile accounts and cash sessions", true],
  ["finance.reverse", "finance", "reverse", "Reverse posted entries", true],
  ["finance.view_profit", "finance", "view_profit", "View profit reporting", true],
  ["reports.view", "reports", "view", "View operational reports", false],
  ["reports.view_financial", "reports", "view_financial", "View financial reports", true],
  ["reports.export", "reports", "export", "Export report data", true],
  ["documents.view", "documents", "view", "View linked documents", false],
  ["documents.upload", "documents", "upload", "Upload protected documents", false],
  ["notifications.view", "notifications", "view", "View personal notifications", false],
  ["approvals.view", "approvals", "view", "View assigned approvals", false],
  ["approvals.decide", "approvals", "decide", "Approve or reject requests", true],
  ["audit.view", "audit", "view", "View immutable audit evidence", true],
  ["audit.export", "audit", "export", "Export audit evidence", true],
  ["management.correct", "management", "correct", "Run management correction workflows", true],
  ["settings.view", "settings", "view", "View system configuration", true],
  ["settings.manage", "settings", "manage", "Change system configuration", true],
  ["search.use", "search", "use", "Use permission-aware global search", false],
  ["tickets.view", "tickets", "view", "View flight booking records", false],
  ["tickets.manage", "tickets", "manage", "Create and update flight bookings", false],
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number][0];

export const PERMISSION_KEYS = new Set<string>(PERMISSIONS.map(([key]) => key));
