import { z } from "zod";

import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, NotFoundError, apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { allocateSequence } from "@/lib/server/sequence";

const reverseSchema = z.object({ reason: z.string().trim().min(5).max(500) });
export async function POST(request: Request, { params }: { params: Promise<{ entryId: string }> }) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "finance.reverse"); const input = await parseJson(request, reverseSchema); const { entryId } = await params; const entry = await db.cashbookEntry.findFirst({ where: { id: entryId, companyId: access.companyId } }); if (!entry) throw new NotFoundError("Finance entry was not found."); requireStation(access, entry.stationId, true); if (!["POSTED", "RECONCILED"].includes(entry.status) || entry.reversalOfId) throw new AppError("ENTRY_NOT_REVERSIBLE", "This entry cannot be reversed.", 409); const result = await db.$transaction(async (tx) => { if (await tx.cashbookEntry.findFirst({ where: { reversalOfId: entry.id } })) throw new AppError("ALREADY_REVERSED", "This entry already has a reversal.", 409); const entryNumber = await allocateSequence(tx, { companyId: access.companyId, stationId: entry.stationId, businessUnitId: entry.businessUnitId ?? undefined, documentType: "CASHBOOK", prefix: "CBR", includeDate: true, padding: 6 }); const reversal = await tx.cashbookEntry.create({ data: { companyId: entry.companyId, stationId: entry.stationId, businessUnitId: entry.businessUnitId, accountId: entry.accountId, categoryId: entry.categoryId, paymentMethodId: entry.paymentMethodId, entryNumber, direction: entry.direction === "CREDIT" ? "DEBIT" : "CREDIT", amount: entry.amount, description: `Reversal of ${entry.entryNumber}`, sourceType: "CashbookReversal", sourceId: entry.id, status: "POSTED", postedById: access.userId, postedAt: new Date(), reversalOfId: entry.id, reversalReason: input.reason } }); await tx.cashbookEntry.update({ where: { id: entry.id }, data: { status: "REVERSED", version: { increment: 1 } } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: entry.stationId, action: "finance.entry_reversed", entityType: "CashbookEntry", entityId: entry.id, reason: input.reason, requestId, before: entry, after: reversal }); return reversal; }); return apiSuccess(result, requestId, { created: true }); } catch (error) { return apiFailure(error, requestId); } }
