import { z } from "zod";
import { Prisma } from "@/lib/generated/prisma/client";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";

const schema = z.discriminatedUnion("type", [z.object({ type: z.literal("COMPANY_PROFILE"), legalName: z.string().trim().min(2).max(200), displayName: z.string().trim().min(2).max(120), email: z.string().email().optional().or(z.literal("")).transform((v) => v || undefined), phone: z.string().trim().max(30).optional(), address: z.string().trim().max(500).optional(), timezone: z.string().trim().min(3).max(80), locale: z.string().trim().min(2).max(20), currencyCode: z.string().trim().length(3).transform((value) => value.toUpperCase()), taxRate: z.string().regex(/^\d+(\.\d{1,4})?$/).optional() }), z.object({ type: z.literal("SETTING"), stationId: z.string().cuid().optional(), businessUnitId: z.string().cuid().optional(), namespace: z.string().trim().min(2).max(80), key: z.string().trim().min(2).max(100), valueType: z.enum(["STRING", "NUMBER", "BOOLEAN", "JSON", "SECRET_REFERENCE"]).default("JSON"), value: z.unknown(), isSensitive: z.boolean().default(false), version: z.number().int().positive().optional() })]);
export async function GET(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "settings.view"); const [company, businessUnits, paymentMethods, settings, cargoLocations] = await Promise.all([db.company.findUniqueOrThrow({ where: { id: access.companyId }, select: { id: true, code: true, legalName: true, displayName: true, email: true, phone: true, address: true, timezone: true, currencyCode: true, locale: true, taxRate: true, logoObjectKey: true, logoDarkObjectKey: true } }), db.businessUnit.findMany({ where: { companyId: access.companyId, isActive: true }, orderBy: { name: "asc" } }), db.paymentMethod.findMany({ where: { companyId: access.companyId }, orderBy: { displayOrder: "asc" } }), db.systemSetting.findMany({ where: { companyId: access.companyId, isSensitive: false, ...(access.companyWide ? {} : { OR: [{ stationId: null, businessUnitId: null }, { stationId: { in: [...access.stationIds] } }] }) }, orderBy: [{ namespace: "asc" }, { key: "asc" }] }), db.cargoLocation.findMany({ where: { companyId: access.companyId }, orderBy: { name: "asc" } })]); const logoUrl = company.logoObjectKey ?? null; const logoDarkUrl = company.logoDarkObjectKey ?? null; return apiSuccess({ company: { ...company, logoUrl, logoDarkUrl }, businessUnits, paymentMethods, settings, cargoLocations }, requestId); } catch (error) { return apiFailure(error, requestId); } }
export async function PUT(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "settings.manage"); const input = await parseJson(request, schema); const result = await db.$transaction(async (tx) => { if (input.type === "COMPANY_PROFILE") { const before = await tx.company.findUniqueOrThrow({ where: { id: access.companyId } }); const updated = await tx.company.update({ where: { id: access.companyId }, data: { legalName: input.legalName, displayName: input.displayName, email: input.email, phone: input.phone, address: input.address, timezone: input.timezone, locale: input.locale, currencyCode: input.currencyCode, ...(input.taxRate !== undefined ? { taxRate: input.taxRate } : {}) } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, action: "settings.company_profile.updated", entityType: "Company", entityId: access.companyId, requestId, before, after: updated }); return updated; } if (input.stationId) requireStation(access, input.stationId, true); const scopeKey = input.stationId ? `STATION:${input.stationId}` : input.businessUnitId ? `BUSINESS_UNIT:${input.businessUnitId}` : "COMPANY"; const existing = await tx.systemSetting.findUnique({ where: { companyId_scopeKey_namespace_key: { companyId: access.companyId, scopeKey, namespace: input.namespace, key: input.key } } }); const value = JSON.parse(JSON.stringify(input.value)) as Prisma.InputJsonValue; const updated = await tx.systemSetting.upsert({ where: { companyId_scopeKey_namespace_key: { companyId: access.companyId, scopeKey, namespace: input.namespace, key: input.key } }, create: { companyId: access.companyId, stationId: input.stationId, businessUnitId: input.businessUnitId, scopeKey, namespace: input.namespace, key: input.key, valueType: input.valueType, value, isSensitive: input.isSensitive, updatedById: access.userId }, update: { valueType: input.valueType, value, isSensitive: input.isSensitive, version: { increment: 1 }, updatedById: access.userId } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: input.stationId, businessUnitId: input.businessUnitId, action: "settings.value.updated", entityType: "SystemSetting", entityId: updated.id, requestId, before: existing, after: updated }); return updated; }); return apiSuccess(result, requestId); } catch (error) { return apiFailure(error, requestId); } }
