import { z } from "zod";

import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, NotFoundError, apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";

const decisionSchema = z.object({ decision: z.enum(["APPROVED", "REJECTED"]), reason: z.string().trim().min(3).max(500) });
export async function POST(request: Request, { params }: { params: Promise<{ entryId: string }> }) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "finance.approve"); const input = await parseJson(request, decisionSchema); const { entryId } = await params; const entry = await db.cashbookEntry.findFirst({ where: { id: entryId, companyId: access.companyId, status: "PENDING_APPROVAL" } }); if (!entry) throw new NotFoundError("Pending finance entry was not found."); requireStation(access, entry.stationId, true); if (entry.postedById === access.userId) throw new AppError("SEGREGATION_OF_DUTIES", "The requester cannot approve their own finance entry.", 403); const result = await db.$transaction(async (tx) => { const updated = await tx.cashbookEntry.update({ where: { id: entry.id }, data: { status: input.decision === "APPROVED" ? "POSTED" : "REJECTED", approvedById: access.userId, postedAt: input.decision === "APPROVED" ? new Date() : undefined } }); await tx.approvalRequest.updateMany({ where: { entityType: "CashbookEntry", entityId: entry.id, status: "PENDING" }, data: { status: input.decision, decidedById: access.userId, decidedAt: new Date(), decisionReason: input.reason } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: entry.stationId, action: `finance.entry_${input.decision.toLowerCase()}`, entityType: "CashbookEntry", entityId: entry.id, reason: input.reason, requestId, before: entry, after: updated }); return updated; }); return apiSuccess(result, requestId); } catch (error) { return apiFailure(error, requestId); } }
