import { z } from "zod";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, NotFoundError, apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { applyStockMovement } from "@/lib/server/inventory";

const schema = z.object({ version: z.number().int().positive(), lines: z.array(z.object({ lineId: z.string().cuid(), quantity: z.string().regex(/^\d+(\.\d{1,3})?$/) })).min(1).max(100) });
export async function POST(request: Request, { params }: { params: Promise<{ transferId: string }> }) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.transfer"); const input = await parseJson(request, schema); const { transferId } = await params; const result = await db.$transaction(async (tx) => { const transfer = await tx.stockTransfer.findFirst({ where: { id: transferId, companyId: access.companyId }, include: { lines: true } }); if (!transfer) throw new NotFoundError("Stock transfer was not found."); requireStation(access, transfer.originStationId, true); if (transfer.status !== "REQUESTED" || transfer.version !== input.version) throw new AppError("TRANSFER_CONFLICT", "Transfer is no longer awaiting dispatch.", 409); if (input.lines.length !== transfer.lines.length) throw new AppError("INVALID_TRANSFER_LINES", "Every transfer line requires a dispatched quantity.", 422); for (const dispatched of input.lines) { const line = transfer.lines.find((item) => item.id === dispatched.lineId); if (!line || line.quantityRequested.lt(dispatched.quantity) || Number(dispatched.quantity) <= 0) throw new AppError("INVALID_DISPATCH_QUANTITY", "A dispatch quantity is invalid.", 422); await applyStockMovement(tx, { companyId: access.companyId, stationId: transfer.originStationId, productId: line.productId, batchId: line.batchId, movementType: "TRANSFER_OUT", quantityDelta: `-${dispatched.quantity}`, referenceType: "StockTransfer", referenceId: transfer.id, reason: transfer.reason, occurredById: access.userId }); await tx.stockTransferLine.update({ where: { id: line.id }, data: { quantityDispatched: dispatched.quantity } }); } const changed = await tx.stockTransfer.updateMany({ where: { id: transfer.id, status: "REQUESTED", version: input.version }, data: { status: "DISPATCHED", dispatchedById: access.userId, dispatchedAt: new Date(), version: { increment: 1 } } }); if (changed.count !== 1) throw new AppError("TRANSFER_CONFLICT", "Transfer was dispatched concurrently.", 409); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: transfer.originStationId, action: "inventory.transfer.dispatched", entityType: "StockTransfer", entityId: transfer.id, requestId, before: transfer, after: { status: "DISPATCHED", lines: input.lines } }); return tx.stockTransfer.findUniqueOrThrow({ where: { id: transfer.id }, include: { lines: true } }); }, { isolationLevel: "Serializable", timeout: 30000, maxWait: 15000 }); return apiSuccess(result, requestId); } catch (error) { return apiFailure(error, requestId); } }
