import { requireAccess, requirePermission } from "@/lib/server/access";
import { AppError, apiFailure, apiSuccess, requestIdFrom } from "@/lib/server/api";
import { db } from "@/lib/server/db";

export async function GET(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "search.use"); const q = new URL(request.url).searchParams.get("q")?.trim(); if (!q || q.length < 2) throw new AppError("SEARCH_TOO_SHORT", "Enter at least two characters.", 422); if (q.length > 120) throw new AppError("SEARCH_TOO_LONG", "Search terms cannot exceed 120 characters.", 422); const station = access.companyWide ? {} : { stationId: { in: [...access.stationIds] } }; const homeStation = access.companyWide ? {} : { homeStationId: { in: [...access.stationIds] } }; const tasks: Array<Promise<unknown>> = []; const keys: string[] = []; const add = (key: string, task: Promise<unknown>) => { keys.push(key); tasks.push(task); };
    if (access.permissions.has("customers.view")) add("customers", db.customer.findMany({ where: { companyId: access.companyId, status: "ACTIVE", ...homeStation, OR: [{ displayName: { contains: q, mode: "insensitive" } }, { primaryPhone: { contains: q } }, { customerNumber: { contains: q, mode: "insensitive" } }, { defaultPnr: { contains: q, mode: "insensitive" } }] }, select: { id: true, customerNumber: true, displayName: true, primaryPhone: true }, take: 8 }));
    if (access.permissions.has("sales.view")) add("sales", db.sale.findMany({ where: { companyId: access.companyId, ...station, OR: [{ saleNumber: { contains: q, mode: "insensitive" } }, { customer: { displayName: { contains: q, mode: "insensitive" } } }] }, select: { id: true, saleNumber: true, total: true, postedAt: true, customer: { select: { displayName: true } } }, orderBy: { postedAt: "desc" }, take: 8 }));
    if (access.permissions.has("inventory.view")) add("products", db.product.findMany({ where: { companyId: access.companyId, OR: [{ name: { contains: q, mode: "insensitive" } }, { code: { contains: q, mode: "insensitive" } }, { barcode: { contains: q } }] }, select: { id: true, code: true, name: true, barcode: true, sellingPrice: true }, take: 8 }));
    if (access.permissions.has("cargo.view")) add("cargo", db.cargoShipment.findMany({ where: { companyId: access.companyId, ...station, OR: [{ awbNumber: { contains: q, mode: "insensitive" } }, { senderName: { contains: q, mode: "insensitive" } }, { receiverName: { contains: q, mode: "insensitive" } }] }, select: { id: true, awbNumber: true, senderName: true, receiverName: true, status: true }, take: 8 }));
    if (access.permissions.has("tickets.view")) add("tickets", db.ticketBooking.findMany({ where: { companyId: access.companyId, ...station, OR: [{ pnr: { contains: q, mode: "insensitive" } }, { bookingNumber: { contains: q, mode: "insensitive" } }, { passengerName: { contains: q, mode: "insensitive" } }] }, select: { id: true, bookingNumber: true, pnr: true, passengerName: true, status: true }, take: 8 }));
    const values = await Promise.all(tasks); return apiSuccess(Object.fromEntries(keys.map((key, index) => [key, values[index]])), requestId); } catch (error) { return apiFailure(error, requestId); } }
