import { z } from "zod";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, apiFailure, apiSuccess, parseJson, parsePagination, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { allocateSequence } from "@/lib/server/sequence";

const schema = z.object({ originStationId: z.string().cuid(), destinationStationId: z.string().cuid(), reason: z.string().trim().min(3).max(500), notes: z.string().trim().max(1000).optional(), lines: z.array(z.object({ productId: z.string().cuid(), batchId: z.string().cuid().optional(), quantity: z.string().regex(/^\d+(\.\d{1,3})?$/) })).min(1).max(100) }).refine((value) => value.originStationId !== value.destinationStationId, { path: ["destinationStationId"], message: "Origin and destination must differ." });
export async function GET(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.view"); const url = new URL(request.url); const { page, pageSize, skip, take } = parsePagination(url.searchParams); const where = { companyId: access.companyId, ...(access.companyWide ? {} : { OR: [{ originStationId: { in: [...access.stationIds] } }, { destinationStationId: { in: [...access.stationIds] } }] }) }; const [items, total] = await Promise.all([db.stockTransfer.findMany({ where, include: { originStation: { select: { id: true, code: true, name: true } }, destinationStation: { select: { id: true, code: true, name: true } }, lines: { include: { product: { select: { id: true, code: true, name: true } } } } }, orderBy: { requestedAt: "desc" }, skip, take }), db.stockTransfer.count({ where })]); return apiSuccess(items, requestId, { page, pageSize, total }); } catch (error) { return apiFailure(error, requestId); } }
export async function POST(request: Request) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.transfer"); const input = await parseJson(request, schema); requireStation(access, input.originStationId, true); requireStation(access, input.destinationStationId); const productIds = [...new Set(input.lines.map((line) => line.productId))]; if ((await db.product.count({ where: { id: { in: productIds }, companyId: access.companyId, status: "ACTIVE" } })) !== productIds.length) throw new AppError("INVALID_PRODUCT", "One or more transfer products are invalid.", 422); const transfer = await db.$transaction(async (tx) => { const transferNumber = await allocateSequence(tx, { companyId: access.companyId, stationId: input.originStationId, documentType: "STOCK_TRANSFER", prefix: "TRF", includeDate: true, padding: 6 }); const created = await tx.stockTransfer.create({ data: { companyId: access.companyId, originStationId: input.originStationId, destinationStationId: input.destinationStationId, transferNumber, requestedById: access.userId, reason: input.reason, notes: input.notes, lines: { create: input.lines.map((line) => ({ productId: line.productId, batchId: line.batchId, quantityRequested: line.quantity })) } }, include: { lines: true } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: input.originStationId, action: "inventory.transfer.requested", entityType: "StockTransfer", entityId: created.id, reason: input.reason, requestId, after: created }); return created; }); return apiSuccess(transfer, requestId, { created: true }); } catch (error) { return apiFailure(error, requestId); } }
