import { z } from "zod";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, NotFoundError, apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { postRefund } from "@/lib/server/refunds";

const schema = z.object({ decision: z.enum(["APPROVED", "REJECTED"]), reason: z.string().trim().min(3).max(500) });
export async function POST(request: Request, { params }: { params: Promise<{ refundId: string }> }) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "approvals.decide"); const input = await parseJson(request, schema); const { refundId } = await params; const result = await db.$transaction(async (tx) => { const refund = await tx.refund.findFirst({ where: { id: refundId, companyId: access.companyId } }); if (!refund) throw new NotFoundError("Refund was not found."); requireStation(access, refund.stationId, true); if (refund.requestedById === access.userId) throw new AppError("SELF_APPROVAL_FORBIDDEN", "The requester cannot decide their own refund.", 409); if (refund.status !== "PENDING_APPROVAL") throw new AppError("REFUND_CONFLICT", "Refund was already decided.", 409); const updated = input.decision === "APPROVED" ? await postRefund(tx, refund.id, access.userId) : await tx.refund.update({ where: { id: refund.id }, data: { status: "REJECTED", approvedById: access.userId } }); await tx.approvalRequest.updateMany({ where: { entityType: "Refund", entityId: refund.id, status: "PENDING" }, data: { status: input.decision, decisionReason: input.reason, decidedById: access.userId, decidedAt: new Date(), version: { increment: 1 } } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: refund.stationId, action: `refund.${input.decision.toLowerCase()}`, entityType: "Refund", entityId: refund.id, reason: input.reason, requestId, before: refund, after: updated }); return updated; }, { isolationLevel: "Serializable" }); return apiSuccess(result, requestId); } catch (error) { return apiFailure(error, requestId); } }
