import { z } from "zod";
import { requireAccess, requirePermission, requireStation } from "@/lib/server/access";
import { AppError, NotFoundError, apiFailure, apiSuccess, parseJson, requestIdFrom } from "@/lib/server/api";
import { writeAudit } from "@/lib/server/audit";
import { db } from "@/lib/server/db";
import { applyStockMovement } from "@/lib/server/inventory";

const schema = z.object({ decision: z.enum(["APPROVED", "REJECTED"]), reason: z.string().trim().min(3).max(500), version: z.number().int().positive() });
export async function POST(request: Request, { params }: { params: Promise<{ adjustmentId: string }> }) { const requestId = requestIdFrom(request); try { const access = requirePermission(await requireAccess(), "inventory.approve_adjustment"); const input = await parseJson(request, schema); const { adjustmentId } = await params; const result = await db.$transaction(async (tx) => { const adjustment = await tx.inventoryAdjustment.findFirst({ where: { id: adjustmentId, companyId: access.companyId }, include: { lines: true } }); if (!adjustment) throw new NotFoundError("Inventory adjustment was not found."); requireStation(access, adjustment.stationId, true); if (adjustment.requestedById === access.userId) throw new AppError("SELF_APPROVAL_FORBIDDEN", "The requester cannot approve their own adjustment.", 409); if (adjustment.status !== "PENDING_APPROVAL" || adjustment.version !== input.version) throw new AppError("ADJUSTMENT_CONFLICT", "Adjustment was already decided.", 409); if (input.decision === "APPROVED") for (const line of adjustment.lines) await applyStockMovement(tx, { companyId: access.companyId, stationId: adjustment.stationId, productId: line.productId, batchId: line.batchId, movementType: "ADJUSTMENT", quantityDelta: line.quantityDelta, referenceType: "InventoryAdjustment", referenceId: adjustment.id, reason: adjustment.reason, occurredById: access.userId }); const updated = await tx.inventoryAdjustment.update({ where: { id: adjustment.id }, data: { status: input.decision === "APPROVED" ? "POSTED" : "REJECTED", approvedById: input.decision === "APPROVED" ? access.userId : undefined, approvedAt: new Date(), postedAt: input.decision === "APPROVED" ? new Date() : undefined, version: { increment: 1 } } }); await tx.approvalRequest.updateMany({ where: { entityType: "InventoryAdjustment", entityId: adjustment.id, status: "PENDING" }, data: { status: input.decision, decisionReason: input.reason, decidedById: access.userId, decidedAt: new Date(), version: { increment: 1 } } }); await writeAudit(tx, { companyId: access.companyId, actorId: access.userId, stationId: adjustment.stationId, action: `inventory.adjustment.${input.decision.toLowerCase()}`, entityType: "InventoryAdjustment", entityId: adjustment.id, reason: input.reason, requestId, before: adjustment, after: updated }); return updated; }, { isolationLevel: "Serializable" }); return apiSuccess(result, requestId); } catch (error) { return apiFailure(error, requestId); } }
